name: Build and upload Conan package
on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install and setup Conan
        uses: conan-io/setup-conan@v1
        with:
          cache_packages: true

      - name: dow_ndk
        run: |
          pwd 
          ls
          sleep 1
          ls
          sh dow_ndk.sh
        with:
            cache_packages: true
      - name: build
        run: |
          conan create . -pr:a android --build=missing
          conan remote login artifactory developer -p ${{ secrets.MY_CONAN_PASSWORD }}
          conan upload "*" --confirm --remote artifactory
