name: Build Conan Package and Compress to ZIP

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-compress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install and setup Conan
        uses: conan-io/setup-conan@v1
        with:
          cache_packages: true

      #- name: Install Android NDK (r27d)
      #  uses: nttld/setup-ndk@v1
      #  id: setup-ndk
      #  with:
      #    ndk-version: r27d
      #    add-to-path: false

      - name: Set ANDROID_NDK_HOME
        run: |
          #echo "ANDROID_NDK_HOME=\"${{ steps.setup-ndk.outputs.ndk-path }}\"" >> $GITHUB_ENV

      - name: Build Conan package
        run: |
          conan install . --build=missing --profile=android #-c tools.android:ndk_path="$ANDROID_NDK_HOME"
          conan create . --profile=android #-c tools.android:ndk_path="$ANDROID_NDK_HOME"

      - name: Find generated files and compress to ZIP
        run: |
          # 假设 Conan 包生成在 ./build 或 ~/.conan/data 目录下
          # 根据实际情况调整路径（例如：查找特定文件或目录）
          OUTPUT_DIR="./build"  # 修改为你的实际输出目录
          ZIP_FILE="conan-build-output.zip"

          # 创建 ZIP 压缩包（包含所有生成的文件）
          zip -r "$ZIP_FILE" "$OUTPUT_DIR"

          # 打印文件列表（调试用）
          echo "ZIP contents:"
          unzip -l "$ZIP_FILE"

      - name: Upload ZIP as artifact
        uses: actions/upload-artifact@v4
        with:
          name: conan-build-archive
          path: conan-build-output.zip