name: Build and upload Conan package

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install and setup Conan
        uses: conan-io/setup-conan@v1
        with:
          cache_packages: true

      - name: Install android-ndk(r27d)
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r27d
          add-to-path: false

      - name: Set ANDROID_NDK_HOME
        run: |
          echo "ANDROID_NDK_HOME=${{ steps.setup-ndk.outputs.ndk-path }}" >> $GITHUB_ENV
          
      - name: Build and upload package
        run: |
          conan create . -pr:a android --build=missing
          conan remote login artifactory developer -p ${{ secrets.MY_CONAN_PASSWORD }}
          conan upload "*" --confirm --remote artifactory